services:
  postgres:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_DB: supportflow
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d supportflow"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure

    
  
  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    
volumes:
  postgres_data: